[tool.poetry]
name = "ex1-loading"
version = "0.1.0"
description = "A quick exercise to learn how some project management libraries work"
authors = ["migteixe"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
pandas = "*"
numpy = "*"
matplotlib = "*"
requests = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"